version: '3.8'
services:
  db:
    image: postgres
    container_name: AdServer
    restart: unless-stopped
    ports:
      - "1001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ytpromarket_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  